package com.cuzz.webac.mapper;

import com.cuzz.webac.model.doo.AccountDO;
import com.cuzz.webac.model.doo.AccountDOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;


@Mapper
public interface AccountDOMapper {


    @Select("SELECT * FROM user_account WHERE email = #{email}")
    @ResultMap("BaseResultMap")
    AccountDO selectByEmail(String email);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    long countByExample(AccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    int deleteByExample(AccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    int insert(AccountDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    int insertSelective(AccountDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    List<AccountDO> selectByExample(AccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    AccountDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    int updateByExampleSelective(@Param("row") AccountDO row, @Param("example") AccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    int updateByExample(@Param("row") AccountDO row, @Param("example") AccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    int updateByPrimaryKeySelective(AccountDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    int updateByPrimaryKey(AccountDO row);
}