package com.cuzz.webac.mapper;

import com.cuzz.webac.model.doo.LogItemDO;
import com.cuzz.webac.model.doo.LogItemDOExample;
import java.util.List;

import com.cuzz.webac.model.vo.ServerPointInfoVO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;

public interface  LogItemDOMapper {


    @Select("SELECT \n" +
            "    FROM_UNIXTIME(FLOOR((TIMESTAMP / 1000) / 600) * 600) AS time_bucket,\n" +
            "    server_name,\n" +
            "    MAX(total_memory) AS total_memory,  -- 使用聚合函数\n" +
            "    MAX(process_memory) AS process_memory,  -- 使用聚合函数\n" +
            "    AVG(used_memory) AS avg_used_memory,  -- 已使用内存的平均值\n" +
            "    AVG(system_cpu_load) AS avg_system_cpu_load,  -- 系统CPU占用的平均值\n" +
            "    AVG(process_cpu_load) AS avg_process_cpu_load  -- 服务器CPU占用的平均值\n" +
            "FROM \n" +
            "    system_monitor_logs\n" +
            "WHERE \n" +
            "    TIMESTAMP BETWEEN UNIX_TIMESTAMP('2025-03-15 00:00:00')*1000 \n" +
            "    AND UNIX_TIMESTAMP('2025-3-16 23:59:59')*1000\n" +
            "GROUP BY \n" +
            "    time_bucket, server_name  -- 没有 total_memory 和 process_memory, 用聚合函数来处理它们\n" +
            "ORDER BY \n" +
            "    time_bucket ASC;\n")
    @Results(id="serverPointsInfo",
            value = {
                    @Result(property = "timeBucket", column = "time_bucket"),
                    @Result(property = "serverName", column = "server_name"),
                    @Result(property = "systemTotalMemory", column = "total_memory"),
                    @Result(property = "processMemory", column = "process_memory"),
                    @Result(property = "avgUsedMemory", column = "avg_used_memory"),
                    @Result(property = "avgProcessCpuLoad", column = "avg_process_cpu_load"),
                    @Result(property = "avgSystemCpuLoad", column = "avg_system_cpu_load")})
    List<ServerPointInfoVO> selectServerPointInfo();




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    long countByExample(LogItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    int deleteByExample(LogItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    int insert(LogItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    int insertSelective(LogItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    List<LogItemDO> selectByExample(LogItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    LogItemDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    int updateByExampleSelective(@Param("row") LogItemDO row, @Param("example") LogItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    int updateByExample(@Param("row") LogItemDO row, @Param("example") LogItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    int updateByPrimaryKeySelective(LogItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    int updateByPrimaryKey(LogItemDO row);
}