package com.cuzz.webac.mapper;

import com.cuzz.webac.model.doo.OrderBelongProductDo;
import com.cuzz.webac.model.doo.OrderBelongProductDoExample;
import java.util.List;

import com.cuzz.webac.model.game.postbox.AdminItem;
import org.apache.ibatis.annotations.*;

public interface OrderBelongProductDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    long countByExample(OrderBelongProductDoExample example);
    @Insert({
            "<script>",
            "INSERT INTO order_products (belong_order_number, product_name, quantity) VALUES",
            "<foreach collection='list' item='product' separator=','>",
            "(#{product.belongOrderNumber}, #{product.productName}, #{product.quantity})",
            "</foreach>",
            "</script>"
    })

    int batchInsertOrderBelongProduct(@Param("list") List<OrderBelongProductDo> orderBelongProductDos);



    @Select({
            "SELECT order_products.product_name, order_products.quantity, products.bukkit_item_base64",
            "FROM order_products",
            "INNER JOIN products ON order_products.product_name = products.product_name",
            "WHERE order_products.belong_order_number = #{orderNumber}"
    })
    @Results({
            @Result(property = "storeID",column = "product_name"),
            @Result(property = "amount",column = "quantity"),
            @Result(property = "base64Item",column = "bukkit_item_base64")
    })
    List<AdminItem> queryAllProductByOrderNumber(String orderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    int deleteByExample(OrderBelongProductDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    int deleteByPrimaryKey(String belongOrderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    int insert(OrderBelongProductDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    int insertSelective(OrderBelongProductDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    List<OrderBelongProductDo> selectByExample(OrderBelongProductDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    OrderBelongProductDo selectByPrimaryKey(String belongOrderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    int updateByExampleSelective(@Param("row") OrderBelongProductDo row, @Param("example") OrderBelongProductDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    int updateByExample(@Param("row") OrderBelongProductDo row, @Param("example") OrderBelongProductDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    int updateByPrimaryKeySelective(OrderBelongProductDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_products
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    int updateByPrimaryKey(OrderBelongProductDo row);
}