package com.cuzz.webac.mapper;

import com.cuzz.webac.model.doo.OrderDO;
import com.cuzz.webac.model.doo.OrderDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface OrderDOMapper {


    // 根据订单号 查询订单支付情况 payment_status要加索引(覆盖索引)
    @Select("SELECT IFNULL(payment_status, -1) FROM orders WHERE order_number = #{orderNumber}")
    byte queryOrderPaymentStatus(String orderNumber);



    //根据订单号 查询订单状态 发货中 取消etc order_status也要加索引
    @Select("SELECT IFNULL(order_status, -1) FROM orders WHERE order_number = #{orderNumber}")
    byte queryOrderStatus(String orderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    long countByExample(OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    int deleteByExample(OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    int insert(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    int insertSelective(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    List<OrderDO> selectByExampleWithBLOBs(OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    List<OrderDO> selectByExample(OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    OrderDO selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    int updateByExampleSelective(@Param("row") OrderDO row, @Param("example") OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") OrderDO row, @Param("example") OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    int updateByExample(@Param("row") OrderDO row, @Param("example") OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    int updateByPrimaryKeySelective(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    int updateByPrimaryKey(OrderDO row);
}