package com.cuzz.webac.mapper;

import com.cuzz.webac.model.doo.ProductDO;
import com.cuzz.webac.model.doo.ProductDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    long countByExample(ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    int deleteByExample(ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    int insert(ProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    int insertSelective(ProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    List<ProductDO> selectByExampleWithBLOBs(ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    List<ProductDO> selectByExample(ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    ProductDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    int updateByExampleSelective(@Param("row") ProductDO row, @Param("example") ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") ProductDO row, @Param("example") ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    int updateByExample(@Param("row") ProductDO row, @Param("example") ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    int updateByPrimaryKeySelective(ProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(ProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    int updateByPrimaryKey(ProductDO row);
}