
server:
  port: 48089

logging:
  config: classpath:config/log4j2.xml
  file:
    path: logs/application.log
  level:
    org.mybatis: DEBUG   # MyBatis SQL 调试日志
    com.zaxxer.hikari: INFO
    org.springframework.jdbc.core: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  application:
    name: WebAC
  web:
    resources:
      static-locations: classpath:/static/
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 1875417678@qq.com
    password: coxlddkceesqcjgc
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  data:
    redis:
      port: 6379
      host: localhost
      timeout: 3000
      password: ""
  datasource:
    url: jdbc:mysql://103.205.253.165:3306/towncraft
    username: root
    password: 0444438a
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  debug: false
jwt:
  secret:
    key: 1ea4367a0765e373acc325d95bbe9415cda8916b98555b95553a48db611064bf
  expiration:
    time: 3600000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #生成的model的路径
  type-aliases-package: com.cuzz.webac.model.doo
pagehelper:
  helper-dialect: mysql  # 数据库方言，这里以 MySQL 为例
  reasonable: true  # 合理化分页，防止出现查询第一页时超过最大页数的情况
  support-methods-arguments: true  # 支持通过方法参数传递分页参数
wechatpay:
  merchantId: 1645631772
  privateKeyPath: "apiclient_key.pem"
  merchantSerialNumber: 6B25891392A197515DDE96A0AB325BAF5292834E
  apiV3Key: A111111111111111111111111111111a
mongodb:
#  url: mongodb://admin:0444438aa@107.172.217.25:27017
  url: mongodb://localhost:27017
#mongodb://admin:0444438aa@107.172.217.25:27017
afybroker:
  # broker 网关服务器地址
  host: localhost
  # broker 网关服务器端口
  port: "11200"
  # 客户端名称 每个客户端应该唯一
  name: 'springx'
  player:
    # 在服务器网关断联后是否踢出全部玩家
    kick-on-close: false
  server:
    # 是否开启 mc 游戏服务器自动注册到 proxy 的功能
    # 若要开启则先确认 broker-bukkit 插件的 config.yml
  sync-enable: false

rocketmq:
  # 临时恢复 NameServer 配置以确保应用启动
#  name-server: localhost:9876  # NameServer
  # 注意：要使用 gRPC Proxy，需要升级到支持的 Spring Boot Starter 版本
  proxy:
    endpoints: 103.205.253.165:15081  # gRPC Proxy 端口
  producer:
    group: shop_group
  consumer:
    group: shop-group
shop:
  #单位秒
  orderTimeOut: 1800
  wechatPaySuccessCallBack: "https://www.4399mc.cn/cuzz/order/wechatOrderCallback"
fromEmail: 1875417678@qq.com
systemUser:
  name: "looklook"
  password: DASIDHAUJDHASIUDH12E412DASHDI
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true



##短信验证码服务
sms:
  host: "https://gyytz.market.alicloudapi.com"
  path: "/sms/smsSend"
  appcode: "1d827d5540c0400fb0297edc4610d8cd"
  smsSignId: "2e65b1bb3d054466b82f0c9d125465e2"
  templateId: "908e94ccf08b4476ba6c876d13f084ad"