version: "3.8"
services:
  namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rmqnamesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876"
    networks: [rocketmq]

  broker:
    image: apache/rocketmq:5.3.2
    container_name: rmqbroker
    command: sh mqbroker
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on: [namesrv]
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    networks: [rocketmq]
    # 可选：持久化
    # volumes:
    #   - ./data/broker/logs:/home/rocketmq/logs
    #   - ./data/broker/store:/home/rocketmq/store

  proxy:
    image: apache/rocketmq:5.3.2
    container_name: rmqproxy
    command: sh mqproxy
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on: [broker, namesrv]
    ports:
      - "8080:8080"   # HTTP
      - "8081:8081"   # gRPC
    restart: on-failure
    networks: [rocketmq]

networks:
  rocketmq:
    driver: bridge
