@startuml
title 用户登录（短信验证码）
'https://plantuml.com/sequence-diagram

autonumber

actor 用户 as User
participant 前端 as FE
participant "Sms服务" as Message
participant "登录服务" as Auth
participant "Redis" as Queue
database "用户账户数据库" as Db
User -> FE: 输入手机号获取验证码
FE -> Message: 给用户发送短信验证码
activate Message
Message --> User: 短信验证码
Message -> Queue: 存储验证码（TTL=30分钟）
note right of Queue: 验证码 30 分钟过期
deactivate Message

User -> FE: 输入手机号+密码+验证码
FE -> Auth: 提交登录
activate Auth
Auth -> Queue: 校验验证码（get + compare）
Auth -> Db: 校验账号密码是否正确（get + compare）
alt 验证码有效+账号密码正确
  Auth --> User: 登录成功
  Auth --> FE : 重定向到首页

else 验证码无效
  Auth --> User: 登录失败
end
deactivate Auth
@enduml
