package com.cuzz.webac.model.doo;

import java.util.Date;

public class AccountDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.id
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.namex
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    private String namex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.email
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.created_at
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.role_id
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.phone
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.statusx
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    private Integer statusx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.last_login_at
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    private Date lastLoginAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.password
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.id
     *
     * @return the value of user_account.id
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.id
     *
     * @param id the value for user_account.id
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.namex
     *
     * @return the value of user_account.namex
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public String getNamex() {
        return namex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.namex
     *
     * @param namex the value for user_account.namex
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public void setNamex(String namex) {
        this.namex = namex == null ? null : namex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.email
     *
     * @return the value of user_account.email
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.email
     *
     * @param email the value for user_account.email
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.created_at
     *
     * @return the value of user_account.created_at
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.created_at
     *
     * @param createdAt the value for user_account.created_at
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.role_id
     *
     * @return the value of user_account.role_id
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.role_id
     *
     * @param roleId the value for user_account.role_id
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.phone
     *
     * @return the value of user_account.phone
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.phone
     *
     * @param phone the value for user_account.phone
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.statusx
     *
     * @return the value of user_account.statusx
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public Integer getStatusx() {
        return statusx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.statusx
     *
     * @param statusx the value for user_account.statusx
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public void setStatusx(Integer statusx) {
        this.statusx = statusx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.last_login_at
     *
     * @return the value of user_account.last_login_at
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public Date getLastLoginAt() {
        return lastLoginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.last_login_at
     *
     * @param lastLoginAt the value for user_account.last_login_at
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public void setLastLoginAt(Date lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.password
     *
     * @return the value of user_account.password
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.password
     *
     * @param password the value for user_account.password
     *
     * @mbg.generated Wed Oct 09 09:58:23 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}