package com.cuzz.webac.model.doo;

import java.math.BigDecimal;

public class LogItemDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_monitor_logs.id
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_monitor_logs.server_name
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    private String serverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_monitor_logs.timestamp
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    private Long timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_monitor_logs.total_memory
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    private Long totalMemory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_monitor_logs.used_memory
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    private Long usedMemory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_monitor_logs.process_memory
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    private Long processMemory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_monitor_logs.system_cpu_load
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    private BigDecimal systemCpuLoad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_monitor_logs.process_cpu_load
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    private BigDecimal processCpuLoad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_monitor_logs.cluster_name
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    private String clusterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_monitor_logs.hostx
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    private String hostx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_monitor_logs.id
     *
     * @return the value of system_monitor_logs.id
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_monitor_logs.id
     *
     * @param id the value for system_monitor_logs.id
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_monitor_logs.server_name
     *
     * @return the value of system_monitor_logs.server_name
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_monitor_logs.server_name
     *
     * @param serverName the value for system_monitor_logs.server_name
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setServerName(String serverName) {
        this.serverName = serverName == null ? null : serverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_monitor_logs.timestamp
     *
     * @return the value of system_monitor_logs.timestamp
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_monitor_logs.timestamp
     *
     * @param timestamp the value for system_monitor_logs.timestamp
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_monitor_logs.total_memory
     *
     * @return the value of system_monitor_logs.total_memory
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public Long getTotalMemory() {
        return totalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_monitor_logs.total_memory
     *
     * @param totalMemory the value for system_monitor_logs.total_memory
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setTotalMemory(Long totalMemory) {
        this.totalMemory = totalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_monitor_logs.used_memory
     *
     * @return the value of system_monitor_logs.used_memory
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public Long getUsedMemory() {
        return usedMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_monitor_logs.used_memory
     *
     * @param usedMemory the value for system_monitor_logs.used_memory
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setUsedMemory(Long usedMemory) {
        this.usedMemory = usedMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_monitor_logs.process_memory
     *
     * @return the value of system_monitor_logs.process_memory
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public Long getProcessMemory() {
        return processMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_monitor_logs.process_memory
     *
     * @param processMemory the value for system_monitor_logs.process_memory
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setProcessMemory(Long processMemory) {
        this.processMemory = processMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_monitor_logs.system_cpu_load
     *
     * @return the value of system_monitor_logs.system_cpu_load
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public BigDecimal getSystemCpuLoad() {
        return systemCpuLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_monitor_logs.system_cpu_load
     *
     * @param systemCpuLoad the value for system_monitor_logs.system_cpu_load
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setSystemCpuLoad(BigDecimal systemCpuLoad) {
        this.systemCpuLoad = systemCpuLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_monitor_logs.process_cpu_load
     *
     * @return the value of system_monitor_logs.process_cpu_load
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public BigDecimal getProcessCpuLoad() {
        return processCpuLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_monitor_logs.process_cpu_load
     *
     * @param processCpuLoad the value for system_monitor_logs.process_cpu_load
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setProcessCpuLoad(BigDecimal processCpuLoad) {
        this.processCpuLoad = processCpuLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_monitor_logs.cluster_name
     *
     * @return the value of system_monitor_logs.cluster_name
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public String getClusterName() {
        return clusterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_monitor_logs.cluster_name
     *
     * @param clusterName the value for system_monitor_logs.cluster_name
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setClusterName(String clusterName) {
        this.clusterName = clusterName == null ? null : clusterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_monitor_logs.hostx
     *
     * @return the value of system_monitor_logs.hostx
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public String getHostx() {
        return hostx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_monitor_logs.hostx
     *
     * @param hostx the value for system_monitor_logs.hostx
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setHostx(String hostx) {
        this.hostx = hostx == null ? null : hostx.trim();
    }
}