package com.cuzz.webac.model.doo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class LogItemDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public LogItemDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andServerNameIsNull() {
            addCriterion("server_name is null");
            return (Criteria) this;
        }

        public Criteria andServerNameIsNotNull() {
            addCriterion("server_name is not null");
            return (Criteria) this;
        }

        public Criteria andServerNameEqualTo(String value) {
            addCriterion("server_name =", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotEqualTo(String value) {
            addCriterion("server_name <>", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameGreaterThan(String value) {
            addCriterion("server_name >", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameGreaterThanOrEqualTo(String value) {
            addCriterion("server_name >=", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLessThan(String value) {
            addCriterion("server_name <", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLessThanOrEqualTo(String value) {
            addCriterion("server_name <=", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLike(String value) {
            addCriterion("server_name like", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotLike(String value) {
            addCriterion("server_name not like", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameIn(List<String> values) {
            addCriterion("server_name in", values, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotIn(List<String> values) {
            addCriterion("server_name not in", values, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameBetween(String value1, String value2) {
            addCriterion("server_name between", value1, value2, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotBetween(String value1, String value2) {
            addCriterion("server_name not between", value1, value2, "serverName");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Long value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Long value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Long value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Long value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Long value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Long value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Long> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Long> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Long value1, Long value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Long value1, Long value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryIsNull() {
            addCriterion("total_memory is null");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryIsNotNull() {
            addCriterion("total_memory is not null");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryEqualTo(Long value) {
            addCriterion("total_memory =", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryNotEqualTo(Long value) {
            addCriterion("total_memory <>", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryGreaterThan(Long value) {
            addCriterion("total_memory >", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryGreaterThanOrEqualTo(Long value) {
            addCriterion("total_memory >=", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryLessThan(Long value) {
            addCriterion("total_memory <", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryLessThanOrEqualTo(Long value) {
            addCriterion("total_memory <=", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryIn(List<Long> values) {
            addCriterion("total_memory in", values, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryNotIn(List<Long> values) {
            addCriterion("total_memory not in", values, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryBetween(Long value1, Long value2) {
            addCriterion("total_memory between", value1, value2, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryNotBetween(Long value1, Long value2) {
            addCriterion("total_memory not between", value1, value2, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryIsNull() {
            addCriterion("used_memory is null");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryIsNotNull() {
            addCriterion("used_memory is not null");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryEqualTo(Long value) {
            addCriterion("used_memory =", value, "usedMemory");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryNotEqualTo(Long value) {
            addCriterion("used_memory <>", value, "usedMemory");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryGreaterThan(Long value) {
            addCriterion("used_memory >", value, "usedMemory");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryGreaterThanOrEqualTo(Long value) {
            addCriterion("used_memory >=", value, "usedMemory");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryLessThan(Long value) {
            addCriterion("used_memory <", value, "usedMemory");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryLessThanOrEqualTo(Long value) {
            addCriterion("used_memory <=", value, "usedMemory");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryIn(List<Long> values) {
            addCriterion("used_memory in", values, "usedMemory");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryNotIn(List<Long> values) {
            addCriterion("used_memory not in", values, "usedMemory");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryBetween(Long value1, Long value2) {
            addCriterion("used_memory between", value1, value2, "usedMemory");
            return (Criteria) this;
        }

        public Criteria andUsedMemoryNotBetween(Long value1, Long value2) {
            addCriterion("used_memory not between", value1, value2, "usedMemory");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryIsNull() {
            addCriterion("process_memory is null");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryIsNotNull() {
            addCriterion("process_memory is not null");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryEqualTo(Long value) {
            addCriterion("process_memory =", value, "processMemory");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryNotEqualTo(Long value) {
            addCriterion("process_memory <>", value, "processMemory");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryGreaterThan(Long value) {
            addCriterion("process_memory >", value, "processMemory");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryGreaterThanOrEqualTo(Long value) {
            addCriterion("process_memory >=", value, "processMemory");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryLessThan(Long value) {
            addCriterion("process_memory <", value, "processMemory");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryLessThanOrEqualTo(Long value) {
            addCriterion("process_memory <=", value, "processMemory");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryIn(List<Long> values) {
            addCriterion("process_memory in", values, "processMemory");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryNotIn(List<Long> values) {
            addCriterion("process_memory not in", values, "processMemory");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryBetween(Long value1, Long value2) {
            addCriterion("process_memory between", value1, value2, "processMemory");
            return (Criteria) this;
        }

        public Criteria andProcessMemoryNotBetween(Long value1, Long value2) {
            addCriterion("process_memory not between", value1, value2, "processMemory");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadIsNull() {
            addCriterion("system_cpu_load is null");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadIsNotNull() {
            addCriterion("system_cpu_load is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadEqualTo(BigDecimal value) {
            addCriterion("system_cpu_load =", value, "systemCpuLoad");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadNotEqualTo(BigDecimal value) {
            addCriterion("system_cpu_load <>", value, "systemCpuLoad");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadGreaterThan(BigDecimal value) {
            addCriterion("system_cpu_load >", value, "systemCpuLoad");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("system_cpu_load >=", value, "systemCpuLoad");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadLessThan(BigDecimal value) {
            addCriterion("system_cpu_load <", value, "systemCpuLoad");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadLessThanOrEqualTo(BigDecimal value) {
            addCriterion("system_cpu_load <=", value, "systemCpuLoad");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadIn(List<BigDecimal> values) {
            addCriterion("system_cpu_load in", values, "systemCpuLoad");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadNotIn(List<BigDecimal> values) {
            addCriterion("system_cpu_load not in", values, "systemCpuLoad");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("system_cpu_load between", value1, value2, "systemCpuLoad");
            return (Criteria) this;
        }

        public Criteria andSystemCpuLoadNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("system_cpu_load not between", value1, value2, "systemCpuLoad");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadIsNull() {
            addCriterion("process_cpu_load is null");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadIsNotNull() {
            addCriterion("process_cpu_load is not null");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadEqualTo(BigDecimal value) {
            addCriterion("process_cpu_load =", value, "processCpuLoad");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadNotEqualTo(BigDecimal value) {
            addCriterion("process_cpu_load <>", value, "processCpuLoad");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadGreaterThan(BigDecimal value) {
            addCriterion("process_cpu_load >", value, "processCpuLoad");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("process_cpu_load >=", value, "processCpuLoad");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadLessThan(BigDecimal value) {
            addCriterion("process_cpu_load <", value, "processCpuLoad");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadLessThanOrEqualTo(BigDecimal value) {
            addCriterion("process_cpu_load <=", value, "processCpuLoad");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadIn(List<BigDecimal> values) {
            addCriterion("process_cpu_load in", values, "processCpuLoad");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadNotIn(List<BigDecimal> values) {
            addCriterion("process_cpu_load not in", values, "processCpuLoad");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("process_cpu_load between", value1, value2, "processCpuLoad");
            return (Criteria) this;
        }

        public Criteria andProcessCpuLoadNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("process_cpu_load not between", value1, value2, "processCpuLoad");
            return (Criteria) this;
        }

        public Criteria andClusterNameIsNull() {
            addCriterion("cluster_name is null");
            return (Criteria) this;
        }

        public Criteria andClusterNameIsNotNull() {
            addCriterion("cluster_name is not null");
            return (Criteria) this;
        }

        public Criteria andClusterNameEqualTo(String value) {
            addCriterion("cluster_name =", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameNotEqualTo(String value) {
            addCriterion("cluster_name <>", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameGreaterThan(String value) {
            addCriterion("cluster_name >", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_name >=", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameLessThan(String value) {
            addCriterion("cluster_name <", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameLessThanOrEqualTo(String value) {
            addCriterion("cluster_name <=", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameLike(String value) {
            addCriterion("cluster_name like", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameNotLike(String value) {
            addCriterion("cluster_name not like", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameIn(List<String> values) {
            addCriterion("cluster_name in", values, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameNotIn(List<String> values) {
            addCriterion("cluster_name not in", values, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameBetween(String value1, String value2) {
            addCriterion("cluster_name between", value1, value2, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameNotBetween(String value1, String value2) {
            addCriterion("cluster_name not between", value1, value2, "clusterName");
            return (Criteria) this;
        }

        public Criteria andHostxIsNull() {
            addCriterion("hostx is null");
            return (Criteria) this;
        }

        public Criteria andHostxIsNotNull() {
            addCriterion("hostx is not null");
            return (Criteria) this;
        }

        public Criteria andHostxEqualTo(String value) {
            addCriterion("hostx =", value, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxNotEqualTo(String value) {
            addCriterion("hostx <>", value, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxGreaterThan(String value) {
            addCriterion("hostx >", value, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxGreaterThanOrEqualTo(String value) {
            addCriterion("hostx >=", value, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxLessThan(String value) {
            addCriterion("hostx <", value, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxLessThanOrEqualTo(String value) {
            addCriterion("hostx <=", value, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxLike(String value) {
            addCriterion("hostx like", value, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxNotLike(String value) {
            addCriterion("hostx not like", value, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxIn(List<String> values) {
            addCriterion("hostx in", values, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxNotIn(List<String> values) {
            addCriterion("hostx not in", values, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxBetween(String value1, String value2) {
            addCriterion("hostx between", value1, value2, "hostx");
            return (Criteria) this;
        }

        public Criteria andHostxNotBetween(String value1, String value2) {
            addCriterion("hostx not between", value1, value2, "hostx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_monitor_logs
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 08 12:39:23 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_monitor_logs
     *
     * @mbg.generated Wed Jan 08 12:39:23 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}