package com.cuzz.webac.model.doo;

import org.springframework.data.annotation.Transient;

public class OrderBelongProductDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.belong_order_number
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    private String belongOrderNumber;

    @Transient
    private ProductDO productDO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.product_name
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.quantity
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.belong_order_number
     *
     * @return the value of order_products.belong_order_number
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    public String getBelongOrderNumber() {
        return belongOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.belong_order_number
     *
     * @param belongOrderNumber the value for order_products.belong_order_number
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    public void setBelongOrderNumber(String belongOrderNumber) {
        this.belongOrderNumber = belongOrderNumber == null ? null : belongOrderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.product_name
     *
     * @return the value of order_products.product_name
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.product_name
     *
     * @param productName the value for order_products.product_name
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.quantity
     *
     * @return the value of order_products.quantity
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.quantity
     *
     * @param quantity the value for order_products.quantity
     *
     * @mbg.generated Sun Feb 23 11:29:57 CST 2025
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}