package com.cuzz.webac.model.doo;

import lombok.Builder;

import java.math.BigDecimal;
import java.util.Date;

@Builder
public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_number
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product_quantity
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private Integer productQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.buyer_name
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private String buyerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.actual_payment
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private BigDecimal actualPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total_discount
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private BigDecimal totalDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.coupon_id
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private Integer couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.payment_method
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private String paymentMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_status
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private Byte orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.payment_status
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private Byte paymentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.created_at
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.updated_at
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.consignee_name
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private String consigneeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.consignee_uuid
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private String consigneeUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.address
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_description
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    private String orderDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_number
     *
     * @return the value of orders.order_number
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_number
     *
     * @param orderNumber the value for orders.order_number
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product_quantity
     *
     * @return the value of orders.product_quantity
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public Integer getProductQuantity() {
        return productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product_quantity
     *
     * @param productQuantity the value for orders.product_quantity
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.buyer_name
     *
     * @return the value of orders.buyer_name
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.buyer_name
     *
     * @param buyerName the value for orders.buyer_name
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.actual_payment
     *
     * @return the value of orders.actual_payment
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public BigDecimal getActualPayment() {
        return actualPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.actual_payment
     *
     * @param actualPayment the value for orders.actual_payment
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setActualPayment(BigDecimal actualPayment) {
        this.actualPayment = actualPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total_discount
     *
     * @return the value of orders.total_discount
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public BigDecimal getTotalDiscount() {
        return totalDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total_discount
     *
     * @param totalDiscount the value for orders.total_discount
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setTotalDiscount(BigDecimal totalDiscount) {
        this.totalDiscount = totalDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.coupon_id
     *
     * @return the value of orders.coupon_id
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.coupon_id
     *
     * @param couponId the value for orders.coupon_id
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.payment_method
     *
     * @return the value of orders.payment_method
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.payment_method
     *
     * @param paymentMethod the value for orders.payment_method
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod == null ? null : paymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_status
     *
     * @return the value of orders.order_status
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_status
     *
     * @param orderStatus the value for orders.order_status
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.payment_status
     *
     * @return the value of orders.payment_status
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public Byte getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.payment_status
     *
     * @param paymentStatus the value for orders.payment_status
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setPaymentStatus(Byte paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.created_at
     *
     * @return the value of orders.created_at
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.created_at
     *
     * @param createdAt the value for orders.created_at
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.updated_at
     *
     * @return the value of orders.updated_at
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.updated_at
     *
     * @param updatedAt the value for orders.updated_at
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.consignee_name
     *
     * @return the value of orders.consignee_name
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.consignee_name
     *
     * @param consigneeName the value for orders.consignee_name
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName == null ? null : consigneeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.consignee_uuid
     *
     * @return the value of orders.consignee_uuid
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public String getConsigneeUuid() {
        return consigneeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.consignee_uuid
     *
     * @param consigneeUuid the value for orders.consignee_uuid
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setConsigneeUuid(String consigneeUuid) {
        this.consigneeUuid = consigneeUuid == null ? null : consigneeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.address
     *
     * @return the value of orders.address
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.address
     *
     * @param address the value for orders.address
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_description
     *
     * @return the value of orders.order_description
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public String getOrderDescription() {
        return orderDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_description
     *
     * @param orderDescription the value for orders.order_description
     *
     * @mbg.generated Sun Jan 05 15:10:16 CST 2025
     */
    public void setOrderDescription(String orderDescription) {
        this.orderDescription = orderDescription == null ? null : orderDescription.trim();
    }
}