package com.cuzz.webac.model.doo;

import java.math.BigDecimal;
import java.util.Date;

public class ProductDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.id
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_type
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private Byte productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.stock
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.current_price
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private BigDecimal currentPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.original_price
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private BigDecimal originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.discount
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_status
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private String productStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.created_at
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.updated_at
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.video_url
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_name
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.bukkit_item_base64
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private String bukkitItemBase64;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.description_text
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    private String descriptionText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.id
     *
     * @return the value of products.id
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.id
     *
     * @param id the value for products.id
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_type
     *
     * @return the value of products.product_type
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public Byte getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_type
     *
     * @param productType the value for products.product_type
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setProductType(Byte productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.stock
     *
     * @return the value of products.stock
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.stock
     *
     * @param stock the value for products.stock
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.current_price
     *
     * @return the value of products.current_price
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public BigDecimal getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.current_price
     *
     * @param currentPrice the value for products.current_price
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setCurrentPrice(BigDecimal currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.original_price
     *
     * @return the value of products.original_price
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.original_price
     *
     * @param originalPrice the value for products.original_price
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.discount
     *
     * @return the value of products.discount
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.discount
     *
     * @param discount the value for products.discount
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_status
     *
     * @return the value of products.product_status
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_status
     *
     * @param productStatus the value for products.product_status
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus == null ? null : productStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.created_at
     *
     * @return the value of products.created_at
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.created_at
     *
     * @param createdAt the value for products.created_at
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.updated_at
     *
     * @return the value of products.updated_at
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.updated_at
     *
     * @param updatedAt the value for products.updated_at
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.video_url
     *
     * @return the value of products.video_url
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.video_url
     *
     * @param videoUrl the value for products.video_url
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_name
     *
     * @return the value of products.product_name
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_name
     *
     * @param productName the value for products.product_name
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.bukkit_item_base64
     *
     * @return the value of products.bukkit_item_base64
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public String getBukkitItemBase64() {
        return bukkitItemBase64;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.bukkit_item_base64
     *
     * @param bukkitItemBase64 the value for products.bukkit_item_base64
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setBukkitItemBase64(String bukkitItemBase64) {
        this.bukkitItemBase64 = bukkitItemBase64 == null ? null : bukkitItemBase64.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.description_text
     *
     * @return the value of products.description_text
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public String getDescriptionText() {
        return descriptionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.description_text
     *
     * @param descriptionText the value for products.description_text
     *
     * @mbg.generated Fri Dec 27 17:12:45 CST 2024
     */
    public void setDescriptionText(String descriptionText) {
        this.descriptionText = descriptionText == null ? null : descriptionText.trim();
    }
}